In [15]:
print("\n=== 🔵 1️⃣ Initialize Ground Truth Labels and Logits ===\n")

import numpy as np

# Ground truth labels (one-hot encoded) with 5 classes
y_true = np.array([
    [1, 0, 0, 0, 0],  # Sample 1: Class 1
    [0, 1, 0, 0, 0],  # Sample 2: Class 2
    [0, 0, 1, 0, 0],  # Sample 3: Class 3
    [0, 0, 0, 1, 0],  # Sample 4: Class 4 (New)
    [0, 0, 0, 0, 1],  # Sample 5: Class 5 (New)
])

# Model predictions (logits) with 5 classes
logits = np.array([
    [2.0, 1.0, 0.1, -0.5, -1.2],  # Sample 1
    [0.5, 2.5, 0.2, 0.1, -0.8],   # Sample 2
    [0.1, 0.2, 3.0, -0.3, -1.5],  # Sample 3
    [1.8, 0.9, 0.2, 2.5, -0.6],   # Sample 4 (New)
    [0.3, 0.1, 2.8, -0.7, 3.2]    # Sample 5 (New)
])

# Print values
print(f"y_true (Ground Truth Labels):\n{y_true}")
print(f"\nlogits (Model Predictions):\n{logits}")


=== 🔵 1️⃣ Initialize Ground Truth Labels and Logits ===

y_true (Ground Truth Labels):
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

logits (Model Predictions):
[[ 2.   1.   0.1 -0.5 -1.2]
 [ 0.5  2.5  0.2  0.1 -0.8]
 [ 0.1  0.2  3.  -0.3 -1.5]
 [ 1.8  0.9  0.2  2.5 -0.6]
 [ 0.3  0.1  2.8 -0.7  3.2]]


In [16]:
print("\n=== 🔵 2️⃣ Define and Apply Softmax Function ===\n")

# Softmax function
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))  # Numerical stability
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

# Compute softmax probabilities
probs = softmax(logits)

# Print softmax output
print("Softmax Probabilities:\n", probs)



=== 🔵 2️⃣ Define and Apply Softmax Function ===

Softmax Probabilities:
 [[0.60964634 0.22427635 0.09118396 0.05004282 0.02485053]
 [0.09927799 0.73357063 0.07354694 0.06654803 0.02705641]
 [0.0472779  0.05225016 0.85923538 0.03169132 0.00954524]
 [0.26932858 0.10950083 0.0543765  0.54236115 0.02443294]
 [0.03072834 0.02515824 0.3743478  0.01130432 0.5584613 ]]


In [17]:
print("\n=== 🔵 3️⃣ Compute Log of Softmax Probabilities ===\n")

# Compute log(probs)
log_probs = np.log(probs)

# Print log probabilities
print("Log of Softmax Probabilities:\n", log_probs)



=== 🔵 3️⃣ Compute Log of Softmax Probabilities ===

Log of Softmax Probabilities:
 [[-0.49487626 -1.49487626 -2.39487626 -2.99487626 -3.69487626]
 [-2.30983139 -0.30983139 -2.60983139 -2.70983139 -3.60983139]
 [-3.05171238 -2.95171238 -0.15171238 -3.45171238 -4.65171238]
 [-1.31182316 -2.21182316 -2.91182316 -0.61182316 -3.71182316]
 [-3.48256996 -3.68256996 -0.98256996 -4.48256996 -0.58256996]]


In [18]:
print("\n=== 🔵 4️⃣ Compute y_true * log(probs) ===\n")

# Compute y_true * log(probs)
y_true_log_probs = y_true * log_probs

# Print element-wise product
print("y_true * log(probs):\n", y_true_log_probs)



=== 🔵 4️⃣ Compute y_true * log(probs) ===

y_true * log(probs):
 [[-0.49487626 -0.         -0.         -0.         -0.        ]
 [-0.         -0.30983139 -0.         -0.         -0.        ]
 [-0.         -0.         -0.15171238 -0.         -0.        ]
 [-0.         -0.         -0.         -0.61182316 -0.        ]
 [-0.         -0.         -0.         -0.         -0.58256996]]


In [19]:
print("\n=== 🔵 5️⃣ Compute CE Loss per Sample ===\n")

# Compute CE loss for each sample
ce_loss = -np.sum(y_true_log_probs, axis=-1)

# Print CE loss for each sample
print("CE Loss per Sample:", ce_loss)



=== 🔵 5️⃣ Compute CE Loss per Sample ===

CE Loss per Sample: [0.49487626 0.30983139 0.15171238 0.61182316 0.58256996]


In [20]:
print("\n=== 🔵 6️⃣ Compute Average CE Loss for the Dataset ===\n")

# Average CE loss for the dataset
avg_ce_loss = np.mean(ce_loss)

# Print average CE loss
print("Average CE Loss for the Dataset:", avg_ce_loss)



=== 🔵 6️⃣ Compute Average CE Loss for the Dataset ===

Average CE Loss for the Dataset: 0.4301626312958994
